### ISSUE TITLE
selectDevice rejects due to indexOf check

### ISSUE THREAD

**Issue by ds8k** [ghenry22/cordova-plugin-chromecastios#12]
When picking a device your JS code performs an indexOf on `devices` and rejects if the device isn't in the array. Unfortunately this means that if I do any manipulation with the list of devices I can't simply pass in an object with the correct keys because the indexOf check will always fail.

Maybe a `find()` would work better? It doesn't make a ton of sense to pass an entire object when all you're using is the deviceId.

**Comment by ghenry22** [comment]
Thanks I will look at adding an alternative method to select device by ID in addition to the existing method

**Comment by ghenry22** [comment]
added 2 new methods in the dev branch, getDeviceList and selectDeviceById which should address this.  Haven't had a chance to test it properly yet but feel free to install from the dev branch and see how you go in the mean time.

https://github.com/ghenry22/cordova-plugin-chromecastios/commit/424bde4aa1f4608d06f60512989d87716872bc54

**Comment by ds8k** [comment]
Awesome! Thank you so much.
