### ISSUE TITLE
Continued development

### ISSUE THREAD

**Issue by RWOverdijk** [ghenry22/cordova-plugin-chromecastios#16]
Cool plugin, thanks.

Quick question, are there plans on continuing development and adding android support, too? We're in need of a plugin to chat with the chrome cast and this plugin seems to be the best option out there, but it only supports iOS.

We already have a semi-functional android version, based on sdk v3 (like this plugin is, if I saw that correctly) so perhaps we can help.

**Comment by ghenry22** [comment]
@RWOverdijk hi yes this plugin will be maintained, I've just been tied up with some other projects lately.  I definitely want to add android and potentially windows universal to this to cover the most common platforms.  If you already have some implementation for android you could share we could work on it together to get it integrated here with a common is interface.

You can message me directly at ghenry22@gmail.com and we can work out the details on how to achieve this.
