### ISSUE TITLE
Plugin is not running on iOS - Maybe problem with iOS 11? 

### ISSUE THREAD

**Issue by NeckbreakerPascal** [ghenry22/cordova-plugin-chromecastios#26]
Hey there,
I am running into a issue after installing the plugin. 

The Plugin installation via cordova plugin add ... works fine, when I then start my app the following is shown:

`ERROR: Plugin 'Chromecast' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.`

I checked the config.xml and the Plugin is there. 

Does anybody has an idea for that issue? Maybe some problem with iOS11? 

Additional errors:
`CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["Chromecast32715239","Chromecast","setup",[]]`

**Comment by djmaxisauce** [comment]
It works for me on ios 11
Maybe its a problem with cordova version.
My ionic info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : [15:03:33] CLI version 3.9.1 [15:03:33] Local version 3.9.1

local packages:

    Cordova Platforms : android 5.2.2 ios 4.5.4
    Ionic Framework   : ionic1 1.3.1

System:

    ios-deploy : 1.9.2 
    Node       : v6.8.1
    npm        : 3.10.8 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

**Comment by NeckbreakerPascal** [comment]
Thanks, the problem is solved. 

It was caused by an older version of cordova platform
